name: "Inform incompatible PRs"
on:
  pull_request:
    branches:
      - main

jobs:
  Check-Compatibility:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_HEAD_REF"
      - run: echo "$GITHUB_BASE_REF"
      - run: echo "hello world"

      - run: echo "${{ github.base_ref }}"

      - run: echo "${{ github.base_ref.sha }}"
      
      - run: echo "$github.base_ref.sha"

      - run: echo "${{ github.event.pull_request.head.sha }}"

      - run: pwd

      - run: ls

      - run: pwd

  Generate-APIDIFF-State:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-PR
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.base_ref }}
          path: tmp/main

      - run: pwd

      - run: ls

      - run: cd tmp

      - run: cd main

      - run: pwd

      - run: ls

      - run: git branch

  Compare-APIDIFF-State:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout-HEAD
        uses: actions/checkout@v2 
      
      - run: pwd

      - run: ls

      - run: git branch
      