name: "Inform Incompatible PRs"
on:
  pull_request:
    branches:
      - main

jobs:
  Check-Compatibility:
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_HEAD_REF"
      - run: echo "$GITHUB_BASE_REF"
      - run: echo "hello world"

      - run: echo "${{ github.base_ref }}"

      - run: echo "${{ github.base_ref.sha }}"
      
      - run: echo "$github.base_ref.sha"

      - run: echo "${{ github.event.pull_request.head.sha }}"

      - run: pwd

      - run: ls

      - run: pwd

  Generate-APIDIFF-State:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout-Main
        uses: actions/checkout@v2
        with: 
          ref: ${{ github.base_ref }}
          path: ${{ github.base_ref }}

      - name: Generate-APIDIFF-State
        run: |
          cd ${{ github.base_ref }}
          make apidiff-build
      
      - name: Checkout-HEAD
        uses: actions/checkout@v2 
        with: 
          path: ${{ github.head_ref }}

      - name: Compare-APIDIFF-State
        run: |
          cd ${{ github.head_ref }}
          pwd
          ls
          git branch
      
      - run: ls
      